//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDShoeReps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int UserID { get; set; }
        public string UserEmail { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserType { get; set; }
        public string IDNumber { get; set; }
        public Nullable<int> ContactNumber { get; set; }
        public string Address { get; set; }
        public string ProfilePicture { get; set; }
    }
}
